name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Get version from tag
        id: tag_name
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build binaries
        run: |
          # macOS AMD64
          GOOS=darwin GOARCH=amd64 go build -o howto-darwin-amd64 .

          # macOS ARM64
          GOOS=darwin GOARCH=arm64 go build -o howto-darwin-arm64 .

          # Linux AMD64
          GOOS=linux GOARCH=amd64 go build -o howto-linux-amd64 .

          # Linux ARM64
          GOOS=linux GOARCH=arm64 go build -o howto-linux-arm64 .

      - name: Create checksums
        run: |
          sha256sum howto-* > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            howto-darwin-amd64
            howto-darwin-arm64
            howto-linux-amd64
            howto-linux-arm64
            checksums.txt
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
